version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web